name: Acquire activation file
on:
  workflow_dispatch:
    inputs:
      value1:
        type: string
        required: true
        description: '20xx'
      value2:
        type: string
        required: true
        description: '.20'
      valu3:
        type: string
        required: true
        description: '.3'
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: {inputs.value1}.{inputs.value2}.{inputs.value3}f1
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
